const ToolNotice = `// This file is generated using Swagger Endpoints Generator (https://github.com/nightmaregaurav/swagger-endpoints-gen)
// It is an automated tool provided by NightmareGaurav (https://github.com/nightmaregaurav)
// Do not edit this file manually except for the lines that are annotated with a comment that ask you to provide a value.`;
